apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-deployment
  labels:
    app: bank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
        - name: bankapp-container
          image: devopsproject1.azurecr.io/bankapp:latest
          ports:
            - containerPort: 8080
